# Generated by Django 5.1.1 on 2024-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, height_field=30, null=True, upload_to='img/', verbose_name='превью', width_field=30),
        ),
    ]
