# Generated by Django 5.1.1 on 2024-10-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='контактный email')),
                ('name', models.CharField(max_length=255, verbose_name='фио')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сooбщения',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='дата начала отправки рассылки')),
                ('finish_at', models.DateTimeField(verbose_name='дата окончания отправки рассылки')),
                ('first_send_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время первой отправки рассылки')),
                ('period', models.CharField(choices=[('w', 'Раз в неделю'), ('d', 'Раз в день'), ('m', 'Раз в месяц')], max_length=1, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('f', 'Завершена'), ('c', 'Создана'), ('p', 'Запущена')], default='c', max_length=1, verbose_name='статус рассылки')),
                ('last_send_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней отправки рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('update_status', 'Может отключать рассылки')],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_at', models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('server_message', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
    ]
